package cn.bitlinks.ems.module.power.dal.dataobject.standingbook.templ;

import cn.bitlinks.ems.framework.mybatis.core.dataobject.BaseDO;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.KeySequence;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.*;

/**
 * 台账模板基础参数 DO
 *
 * @author bitlinks
 */
@TableName("power_standingbook_templ_attr")
@KeySequence("power_standingbook_templ_attr_seq") // 用于 Oracle、PostgreSQL、Kingbase、DB2、H2 数据库的主键自增。如果是 MySQL 等数据库，可不写。
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class StandingbookTemplAttrDO extends BaseDO {

    /**
     * 模板id
     */
    @TableId(value = "id", type = IdType.ASSIGN_ID)
    private Long id;
    /**
     * 台账分类id
     */
    private Long typeId;
    /**
     * 属性名字
     */
    private String name;
    /**
     * 是否必填
     */
    private String isRequired;
    /**
     * 编码
     */
    private String code;
    /**
     * 排序
     */
    private Long sort;
    /**
     * 格式
     */
    private String format;
    /**
     * 简介
     */
    private String description;
    /**
     * 非自定义属性的源属性id
     */
    private Long rawAttrId;
    /**
     * 源属性归属节点(台账分类id)
     */
    private Long nodeId;
    /**
     * 是否自定义属性，0是系统继承属性，1是模板私有属性
     */
    private String autoGenerated;
    /**
     * 是否展示（系统内置祖宗节点的固定属性会展示到查询条件上）
     */
    private String displayFlag;

}