package cn.bitlinks.ems.module.power.controller.admin.standingbook.tmpl.vo;

import com.alibaba.excel.annotation.ExcelProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.time.LocalDateTime;

@Schema(description = "管理后台 - 台账属性 Response VO")
@Data
public class StandingbookTmplDaqAttrSbRespVO {

    @Schema(description = "编号")
    private Long id;

    @Schema(description = "类型编号")
    private Long typeId;
    @Schema(description = "台账id")
    private Long sbId;
    @Schema(description = "所属能源id")
    private Long energyId;

    @Schema(description = "是否能源数采参数 0自定义数采 1能源数采")
    private Boolean energyFlag;

    @Schema(description = "参数名称")
    private String parameter;


    @Schema(description = "编码")
    private String code;

    @Schema(description = "排序")
    private Integer sort;

    @Schema(description = "数据特征")
    private Integer dataFeature;

    @Schema(description = "单位")
    private String unit;

    @Schema(description = "数据类型")
    private Integer dataType;

    @Schema(description = "用量")
    private Integer usage;

    @Schema(description = "归属节点")
    @ExcelProperty("归属节点")
    private String node;

    @Schema(description = "归属节点id")
    @ExcelProperty("归属节点id")
    private Long nodeId;

    @Schema(description = "是否自动生成", example = "0")
    private String autoGenerated;

    @Schema(description = "是否启用")
    private Boolean status;

    @Schema(description = "创建时间", requiredMode = Schema.RequiredMode.REQUIRED)
    @ExcelProperty("创建时间")
    private LocalDateTime createTime;

    @Schema(description = "创建人名称")
    private String createByName;

    @Schema(description = "创建人")
    private String creator;


}
