package cn.bitlinks.ems.module.power.dal.dataobject.standingbook.tmpl;

import cn.bitlinks.ems.framework.mybatis.core.dataobject.BaseDO;
import com.baomidou.mybatisplus.annotation.*;
import lombok.*;

/**
 * 台账分类的数采参数表（自定义和能源） DO
 *
 * @author bitlinks
 */
@TableName("power_standingbook_tmpl_daq_attr")
@KeySequence("power_standingbook_tmpl_daq_attr_seq")
// 用于 Oracle、PostgreSQL、Kingbase、DB2、H2 数据库的主键自增。如果是 MySQL 等数据库，可不写。
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class StandingbookTmplDaqAttrDO extends BaseDO {

    /**
     * 分类数采参数属性id
     */
    @TableId(value = "id", type = IdType.ASSIGN_ID)
    private Long id;
    /**
     * 台账分类id
     */
    private Long typeId;
    /**
     * 所属能源id
     */
    private Long energyId;
    /**
     * 是否能源数采参数 0自定义数采 1能源数采
     */
    private Boolean energyFlag;
    /**
     * 能源参数id
     */
    private Long parameterId;
    /**
     * 参数名称
     */
    private String parameter;
    /**
     * 编码
     */
    private String code;
    /**
     * 数据特征
     */
    private Integer dataFeature;
    /**
     * 单位
     */
    private String unit;
    /**
     * 数据类型
     */
    private Integer dataType;
    /**
     * 用量
     */
    @TableField(value = "`usage`")
    private Integer usage;
    /**
     * 数采源属性id
     */
    private Long rawAttrId;
    /**
     * 源属性归属节点(台账分类id)
     */
    private Long nodeId;
    /**
     * 是否自定义属性，0是系统继承属性，1是模板私有属性
     */
    private String autoGenerated;
    /**
     * 是否启用
     */
    private Boolean status;
    /**
     * 排序
     */
    private Integer sort;
}